// import fs from 'fs';
// import { readdirSync } from 'fs';
// import Link from 'next/link';

import Head from 'next/head';

// const getPostMetadata = () => {
//   const files = readdirSync('posts/');
//   const slugs = files
//     .filter((file) => file.endsWith('.md'))
//     .map((file) => file.replace('.md', ''));

//   return slugs;
// };

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Emerson Paiva</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>Posts</main>
    </>
  );
};

export default HomePage;
