import { BioResume } from 'components/BioResume'
import { BlogList } from 'components/BlogList'
import { HomePage } from 'components/Pages/HomePage'
import { getAllPosts } from 'lib/api'
import type { NextPage } from 'next'
import Head from 'next/head'

type Posts = {
  title: string
  slug: string
  date: string
  thumbnail: string
  timeToRead: number
}

type HomeProps = {
  allPosts: Posts[]
}

const Home = ({ allPosts }: HomeProps & NextPage) => (
  <>
    <Head>
      <title>Home | Emerson Paiva</title>
      {/* <meta name="description" content="Generated by create next app" /> */}
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <HomePage>
      <BioResume />
      <BlogList posts={allPosts} />
    </HomePage>
  </>
)

export const getStaticProps = async () => {
  const allPosts = getAllPosts([
    'title',
    'date',
    'slug',
    'thumbnail',
    'timeToRead',
  ])

  return {
    props: { allPosts },
  }
}

export default Home
